const ON_CHANGE = 'ON_CHANGE';
const ON_FOCUS = 'ON_FOCUS';
const ON_BLUR = 'ON_BLUR';
const SUBMIT = 'SUBMIT';
const RECEIVE_DATA = 'RECEIVE_DATA';
const BUTTON_STATUS = 'BUTTON_STATUS';

export default {
  ON_CHANGE,
  ON_FOCUS,
  ON_BLUR,
  SUBMIT,
  RECEIVE_DATA,
  BUTTON_STATUS,
};
